version: "3.8"

services:
  backend:
    build:
      context: ./backend
    image: crawler/backend
    depends_on:
      - db
    volumes:
      - ./backend/src/:/app/src/
      - /etc/localtime:/etc/localtime
    ports:
      - 8080:${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USER: ${DB_USER}
      DATABASE_PASS: ${DB_PASS}
      DATABASE_URI: ${DB_URI}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

  db:
    image: mongo:7.0
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

  redis:
    image: redis:7.2.5-alpine
    ports:
      - 6379:6379

  frontend:
    build: ./frontend
    ports:
      - 80:80
    environment:
      - BACKEND_URL=http://backend:${SERVER_PORT}

volumes:
  mongo-data:
